version: '3.8'

services:
  extcntr-container:
    build:
      context: .
      dockerfile: Dockerfile.extcntr
    image: extcntr-dind-container
    container_name: extcntr-container
    privileged: true
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/fuse
    volumes:
      - ./workspace:/workspace
      - /lib/modules:/lib/modules:ro  # Mount host kernel modules
