version: '3.8'

services:
  cntr_extfuse:
    build:
      context: .
      dockerfile: Dockerfile.extcntr
    image: cntr_extfuse_image
    container_name: cntr_extfuse
    privileged: true
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/fuse
    volumes:
      - ./workspace:/workspace
