version: '3.8'

services:
  cntr_fuse:
    build:
      context: .
      dockerfile: Dockerfile.cntr
    image: cntr_fuse_image
    container_name: cntr_fuse
    privileged: true  # Required for Docker-in-Docker
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/fuse
    volumes:
      - ./workspace:/workspace  # Workspace directory for slim and fat container files
    stdin_open: true
    tty: true
