# Base image using a lightweight Linux distribution
FROM debian:latest

# Install SQLite
RUN apt-get update && \
    apt-get install -y sqlite3 && \
    apt-get clean

# Copy the workload script
COPY workload.sh /workload.sh

# Make the script executable
RUN chmod +x /workload.sh

# Start a bash shell by default
ENTRYPOINT ["sh", "-c", "/workload.sh; tail -f /dev/null"]
